spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ebanking?createDatabaseIfNotExist=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  mail:
    host: smtp.gmail.com
    port: 587
    username: etafweb2021@gmail.com
    password: vrwjtiartfqihntf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
    show-sql: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  sql:
    init:
      mode: always

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

server:
  port: 8200
